/* Problem:
Declare three variables (name, age, city)
and print them using console.log().*/



// Store name in a variable
let name = "Subhadeep";

// Store age in a variable
let age = 22;

// Store city in a variable
let city = "Kolkata";

// Print name
console.log("Name:", name);

// Print age
console.log("Age:", age);

// Print city
console.log("City:", city);







/*Problem:
Swap two numbers using a third variable.*/




// Declare first variable
let a = 10;

// Declare second variable
let b = 20;

// Print values before swapping
console.log("Before Swapping");
console.log("a =", a);
console.log("b =", b);

// Create a temporary variable
let temp = a;

// Store b inside a
a = b;

// Store temp inside b
b = temp;

// Print values after swapping
console.log("After Swapping");
console.log("a =", a);
console.log("b =", b);